#
# TABLE STRUCTURE FOR: BOOK_LANGUAGE
#

DROP TABLE IF EXISTS `BOOK_LANGUAGE`;

CREATE TABLE `BOOK_LANGUAGE` (
  `LANGUAGE_ID` int(11) NOT NULL,
  `LANGUAGE_NAME` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`LANGUAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (8, 'architecto');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (32, 'ea');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (34, 'asperiores');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (35, 'cum');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (36, 'blanditiis');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (47, 'repudiandae');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (61, 'esse');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (67, 'qui');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (73, 'ut');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (75, 'velit');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (78, 'eum');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (83, 'ut');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (85, 'id');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (92, 'voluptatem');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (113, 'cupiditate');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (136, 'maxime');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (139, 'dolorum');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (145, 'et');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (153, 'alias');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (172, 'qui');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (200, 'quia');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (234, 'sint');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (237, 'quis');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (243, 'delectus');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (245, 'odit');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (249, 'deleniti');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (264, 'perferendis');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (267, 'officiis');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (272, 'omnis');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (277, 'accusamus');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (279, 'nihil');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (281, 'debitis');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (292, 'eum');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (295, 'quia');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (322, 'quas');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (335, 'iure');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (357, 'non');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (365, 'neque');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (366, 'unde');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (380, 'non');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (402, 'quis');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (404, 'unde');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (435, 'saepe');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (444, 'inventore');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (459, 'mollitia');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (476, 'rerum');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (492, 'sequi');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (524, 'beatae');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (526, 'dicta');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (553, 'placeat');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (558, 'aut');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (569, 'perferendis');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (577, 'quod');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (585, 'nihil');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (595, 'qui');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (598, 'commodi');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (603, 'sit');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (605, 'laborum');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (607, 'velit');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (608, 'ut');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (616, 'delectus');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (618, 'dolorum');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (623, 'aut');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (626, 'culpa');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (632, 'excepturi');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (640, 'ut');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (644, 'ab');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (686, 'harum');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (688, 'explicabo');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (698, 'placeat');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (706, 'tenetur');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (708, 'nemo');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (710, 'fuga');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (723, 'et');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (737, 'ratione');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (745, 'illo');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (750, 'distinctio');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (757, 'eius');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (770, 'placeat');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (771, 'debitis');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (795, 'magni');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (809, 'dolor');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (831, 'deleniti');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (832, 'aut');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (848, 'officiis');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (850, 'et');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (860, 'incidunt');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (875, 'aut');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (878, 'maxime');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (886, 'mollitia');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (898, 'nemo');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (901, 'error');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (941, 'eveniet');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (953, 'vel');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (954, 'quod');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (957, 'voluptas');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (980, 'excepturi');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (981, 'odio');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (988, 'repudiandae');
INSERT INTO `BOOK_LANGUAGE` (`LANGUAGE_ID`, `LANGUAGE_NAME`) VALUES (999, 'quos');


