#
# TABLE STRUCTURE FOR: BOOK_CAT
#

DROP TABLE IF EXISTS `BOOK_CAT`;

CREATE TABLE `BOOK_CAT` (
  `BOOK_CAT_ID` int(11) NOT NULL,
  `FICTION` varchar(30) DEFAULT NULL,
  `NONFICTION` varchar(30) DEFAULT NULL,
  `SPECIALTY` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`BOOK_CAT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (5, 'fuga', 'voluptates', 'nesciunt');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (30, 'repudiandae', 'vitae', 'neque');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (43, 'quaerat', 'quidem', 'quasi');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (49, 'voluptatibus', 'alias', 'repellendus');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (52, 'necessitatibus', 'dolorum', 'voluptas');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (58, 'quia', 'qui', 'enim');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (59, 'magni', 'ut', 'ut');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (68, 'voluptas', 'sint', 'fuga');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (72, 'nam', 'iste', 'cumque');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (73, 'velit', 'molestiae', 'et');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (101, 'rem', 'saepe', 'ut');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (102, 'corporis', 'nostrum', 'magnam');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (107, 'minus', 'quibusdam', 'quasi');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (128, 'temporibus', 'neque', 'vel');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (142, 'omnis', 'praesentium', 'dolor');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (151, 'molestias', 'tenetur', 'eum');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (211, 'rerum', 'voluptatem', 'ratione');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (234, 'quia', 'tempora', 'quia');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (236, 'iusto', 'facilis', 'iusto');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (264, 'fugit', 'eveniet', 'eligendi');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (267, 'ea', 'in', 'commodi');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (271, 'aperiam', 'aut', 'et');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (279, 'debitis', 'est', 'fuga');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (280, 'rerum', 'ducimus', 'et');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (300, 'consequatur', 'omnis', 'dolor');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (310, 'repellat', 'ad', 'fuga');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (328, 'dolorum', 'vel', 'ea');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (330, 'debitis', 'ducimus', 'numquam');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (331, 'autem', 'ea', 'vero');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (350, 'repellat', 'autem', 'sequi');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (366, 'neque', 'dolorem', 'laborum');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (367, 'reprehenderit', 'minima', 'unde');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (373, 'tempore', 'rerum', 'molestiae');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (374, 'placeat', 'et', 'dolorem');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (377, 'quae', 'illo', 'earum');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (382, 'voluptas', 'qui', 'eaque');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (404, 'nesciunt', 'eos', 'repudiandae');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (414, 'placeat', 'modi', 'quos');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (426, 'mollitia', 'minima', 'ullam');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (433, 'blanditiis', 'autem', 'earum');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (475, 'eos', 'ducimus', 'voluptas');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (482, 'neque', 'praesentium', 'nulla');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (491, 'dolores', 'quia', 'reprehenderit');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (495, 'porro', 'ducimus', 'odit');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (497, 'consequatur', 'nulla', 'ut');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (517, 'dolorem', 'velit', 'minima');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (532, 'laboriosam', 'aut', 'dolorem');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (550, 'delectus', 'sed', 'et');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (551, 'harum', 'pariatur', 'consectetur');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (559, 'ratione', 'quisquam', 'sed');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (589, 'dolores', 'ipsa', 'vel');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (600, 'sint', 'ut', 'harum');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (631, 'minus', 'commodi', 'officia');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (634, 'porro', 'odit', 'voluptatem');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (644, 'consequatur', 'sint', 'eius');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (656, 'sapiente', 'itaque', 'et');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (665, 'et', 'dolorem', 'minus');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (681, 'quibusdam', 'laborum', 'beatae');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (689, 'itaque', 'harum', 'sed');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (690, 'voluptatem', 'velit', 'reprehenderit');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (709, 'non', 'vel', 'deleniti');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (714, 'similique', 'ab', 'harum');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (715, 'eligendi', 'est', 'fugit');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (728, 'aut', 'numquam', 'ut');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (735, 'soluta', 'quibusdam', 'autem');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (737, 'nihil', 'veniam', 'eligendi');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (740, 'eos', 'ut', 'repellat');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (741, 'cum', 'non', 'aliquam');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (745, 'modi', 'consequatur', 'eos');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (747, 'ipsum', 'earum', 'in');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (756, 'quia', 'maiores', 'rerum');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (763, 'eaque', 'qui', 'omnis');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (768, 'quasi', 'assumenda', 'a');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (769, 'dolor', 'ipsa', 'incidunt');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (770, 'omnis', 'excepturi', 'aut');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (777, 'eum', 'ut', 'officiis');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (790, 'vitae', 'omnis', 'qui');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (792, 'repudiandae', 'eum', 'consequuntur');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (826, 'mollitia', 'unde', 'rem');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (828, 'ut', 'ut', 'veritatis');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (834, 'consequatur', 'sed', 'neque');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (838, 'in', 'occaecati', 'nam');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (844, 'totam', 'maiores', 'dolorum');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (856, 'vero', 'harum', 'ab');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (857, 'blanditiis', 'ea', 'est');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (864, 'repudiandae', 'aut', 'nemo');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (882, 'ratione', 'earum', 'hic');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (885, 'voluptatum', 'vitae', 'in');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (893, 'asperiores', 'voluptas', 'quisquam');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (898, 'nobis', 'nostrum', 'quia');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (906, 'ut', 'sint', 'fuga');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (909, 'nemo', 'voluptatibus', 'dolorum');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (916, 'corporis', 'qui', 'esse');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (918, 'facilis', 'numquam', 'illo');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (926, 'autem', 'est', 'vitae');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (933, 'ratione', 'quam', 'est');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (954, 'repellat', 'repudiandae', 'ea');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (956, 'hic', 'hic', 'sit');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (981, 'est', 'error', 'est');
INSERT INTO `BOOK_CAT` (`BOOK_CAT_ID`, `FICTION`, `NONFICTION`, `SPECIALTY`) VALUES (999, 'sunt', 'quia', 'unde');


