#
# TABLE STRUCTURE FOR: PUBLISHER
#

DROP TABLE IF EXISTS `PUBLISHER`;

CREATE TABLE `PUBLISHER` (
  `PUBLISHER_ID` int(11) NOT NULL,
  `PUBLICATION_NAME` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`PUBLISHER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (11, 'quas');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (32, 'nihil');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (47, 'voluptatem');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (52, 'dolorem');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (53, 'voluptates');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (85, 'aut');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (90, 'maiores');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (112, 'quas');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (136, 'aut');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (139, 'soluta');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (144, 'amet');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (150, 'et');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (174, 'nesciunt');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (177, 'quaerat');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (182, 'similique');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (191, 'beatae');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (207, 'minima');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (227, 'dicta');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (229, 'aliquam');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (232, 'provident');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (243, 'praesentium');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (262, 'autem');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (271, 'dicta');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (285, 'sint');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (299, 'soluta');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (307, 'ab');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (312, 'non');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (324, 'cum');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (341, 'aut');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (343, 'et');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (359, 'voluptates');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (360, 'dicta');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (365, 'nihil');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (380, 'aut');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (388, 'molestias');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (408, 'ea');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (429, 'rem');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (460, 'aliquid');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (471, 'mollitia');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (474, 'in');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (475, 'nostrum');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (477, 'dicta');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (493, 'est');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (494, 'labore');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (496, 'quibusdam');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (500, 'veritatis');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (535, 'accusamus');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (540, 'est');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (543, 'dolorem');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (566, 'officia');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (581, 'voluptates');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (582, 'laboriosam');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (594, 'quasi');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (597, 'expedita');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (598, 'dolores');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (610, 'reprehenderit');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (614, 'voluptatem');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (615, 'veritatis');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (629, 'in');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (630, 'adipisci');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (640, 'quibusdam');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (645, 'veniam');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (646, 'quam');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (657, 'sint');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (672, 'fugiat');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (677, 'consequatur');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (688, 'qui');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (689, 'laudantium');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (701, 'facere');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (710, 'corrupti');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (736, 'quibusdam');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (744, 'non');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (749, 'sed');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (758, 'incidunt');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (759, 'nemo');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (769, 'dolores');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (771, 'dolor');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (776, 'excepturi');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (777, 'cum');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (784, 'non');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (812, 'dolor');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (827, 'hic');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (832, 'voluptatem');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (834, 'inventore');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (838, 'labore');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (858, 'cumque');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (878, 'aut');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (888, 'ullam');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (898, 'sunt');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (917, 'et');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (922, 'consequuntur');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (929, 'beatae');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (942, 'suscipit');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (946, 'quis');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (958, 'laborum');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (968, 'ducimus');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (979, 'ut');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (985, 'qui');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (990, 'qui');
INSERT INTO `PUBLISHER` (`PUBLISHER_ID`, `PUBLICATION_NAME`) VALUES (992, 'rem');


