#
# TABLE STRUCTURE FOR: VENDOR
#

DROP TABLE IF EXISTS `VENDOR`;

CREATE TABLE `VENDOR` (
  `VENDOR_ID` int(11) NOT NULL,
  `VENDOR_NAME` varchar(30) DEFAULT NULL,
  `VENDOR_PHONE` char(12) DEFAULT NULL,
  `VENDOR_AREACODE` char(3) DEFAULT NULL,
  `VENDOR_STATE` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`VENDOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (5, 'Mr. Stephen Feeney', '541-503-0937', '298', 'Michigan');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (7, 'Lamont Becker', '1-639-772-59', '816', 'Massachusetts');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (17, 'Forest D\'Amore V', '04452559107', '774', 'California');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (32, 'Merl Braun', '+26(1)283620', '846', 'Virginia');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (41, 'Sydney Kuhn', '317-999-6781', '020', 'NewJersey');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (43, 'Brielle Wilderman DDS', '1-314-956-18', '923', 'Kentucky');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (54, 'Adalberto Farrell', '+27(3)034279', '904', 'Louisiana');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (67, 'Prof. Patricia Deckow', '750.658.0317', '887', 'NewYork');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (74, 'Shannon Towne', '003-796-2817', '385', 'Alabama');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (84, 'Mrs. Trisha Sawayn', '1-624-410-40', '404', 'Massachusetts');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (86, 'Nicolette Cummings', '+41(8)112585', '556', 'Ohio');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (91, 'Libby Mosciski', '(046)625-604', '195', 'Massachusetts');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (92, 'Prof. Trevor Brekke', '(557)909-641', '235', 'NewMexico');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (109, 'Lenore Skiles DVM', '804.966.3485', '763', 'Missouri');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (115, 'Dr. Gerardo Stracke', '771.590.4241', '532', 'Michigan');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (130, 'Arno Nader', '+68(0)187103', '616', 'Tennessee');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (131, 'Prof. Athena White', '(375)510-025', '897', 'NewMexico');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (132, 'Wilford Dickinson', '602-770-5438', '485', 'NewMexico');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (138, 'Prof. Orland Abshire I', '963-899-0672', '070', 'Virginia');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (144, 'Mrs. Jannie Thiel', '06092982924', '858', 'Nebraska');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (157, 'Cortney Hegmann', '07311608187', '711', 'Wisconsin');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (165, 'Veda Walsh', '659.059.6663', '877', 'Idaho');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (199, 'Enid Zulauf', '1-570-905-42', '044', 'Missouri');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (201, 'Jed DuBuque', '294.109.2871', '942', 'Minnesota');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (202, 'Baby Mertz', '471-251-8577', '334', 'Wyoming');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (207, 'Jazmyn Kautzer', '042-231-5953', '310', 'NorthCarolina');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (221, 'Kelton Hessel', '(929)459-238', '624', 'Colorado');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (228, 'Dillon O\'Kon', '(927)533-423', '289', 'Texas');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (234, 'Elmira Renner', '(424)884-337', '868', 'Minnesota');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (244, 'Danielle Swift', '233-860-8127', '952', 'Arkansas');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (246, 'Alfred Walter', '876-046-5047', '149', 'Tennessee');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (248, 'Lyric Davis IV', '(167)743-120', '357', 'Idaho');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (249, 'Alanna King Jr.', '083.179.5517', '747', 'Alaska');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (268, 'Lilyan Waelchi', '00142810485', '640', 'SouthCarolina');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (277, 'Miss Annabel Fisher V', '667.956.4797', '222', 'NewJersey');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (286, 'Guido Jenkins', '714.660.9593', '898', 'Vermont');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (290, 'Lauriane Boyle', '+28(3)330725', '676', 'Mississippi');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (308, 'Ralph Jerde', '918-655-1428', '145', 'Kansas');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (309, 'Telly Fay', '03349936189', '468', 'Virginia');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (326, 'Llewellyn Prosacco Jr.', '+11(2)328865', '692', 'Kansas');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (390, 'Jewell Mueller V', '438.199.7384', '826', 'District of Columbia');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (393, 'Mr. Uriel Shanahan MD', '1-750-796-41', '558', 'NewYork');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (398, 'Maryjane Romaguera', '937.452.6898', '578', 'Tennessee');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (406, 'Verlie Jones', '08425697178', '815', 'WestVirginia');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (420, 'Dr. Janet Hintz I', '1-338-670-49', '144', 'Tennessee');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (442, 'Mr. Jerrell Zboncak', '801-016-5539', '510', 'Washington');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (445, 'Janice Corwin DDS', '822-031-4087', '899', 'Oklahoma');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (449, 'Miss Pink Marks IV', '742-415-8523', '587', 'Arizona');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (451, 'Arnoldo Schinner', '244.291.6567', '649', 'Illinois');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (452, 'Winifred O\'Kon V', '(007)118-480', '330', 'Nevada');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (454, 'Miss Mariah Shields V', '843-317-3969', '955', 'Arkansas');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (477, 'Isabella Thompson II', '1-650-577-20', '615', 'Minnesota');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (480, 'Kamron Kshlerin', '922.663.9661', '667', 'RhodeIsland');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (481, 'Donnie Gibson DVM', '667.743.8298', '723', 'Oregon');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (485, 'Ms. Reanna Pouros', '1-201-911-49', '684', 'Massachusetts');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (514, 'Asa Conn Sr.', '577-362-2438', '718', 'Hawaii');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (515, 'Titus Swift', '1-186-838-37', '825', 'Oklahoma');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (541, 'Mustafa Kuhic', '003.551.2984', '073', 'Washington');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (571, 'Prof. Rowena Thiel DDS', '+41(2)294215', '170', 'Pennsylvania');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (577, 'Patricia Moen', '1-847-892-15', '034', 'Minnesota');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (579, 'Stan Daugherty', '09967012379', '380', 'Washington');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (591, 'Oliver Ledner', '1-836-234-47', '840', 'Alaska');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (601, 'Winona Bruen', '178-116-1744', '692', 'SouthDakota');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (603, 'Devyn Cronin', '120-032-5057', '489', 'NewYork');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (605, 'Dr. Ayana Littel II', '(504)813-859', '347', 'Delaware');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (632, 'Imani Block', '01746741429', '516', 'Iowa');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (651, 'Esmeralda Borer', '136.576.2535', '518', 'Missouri');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (668, 'Claudie Moen', '+89(6)353201', '765', 'Alaska');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (692, 'Mr. Johnnie Wintheiser II', '453.447.3728', '186', 'Louisiana');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (707, 'Miss Katarina Carroll II', '+70(4)740359', '114', 'Montana');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (722, 'Zella Barrows', '1-706-142-45', '504', 'Louisiana');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (726, 'Milford Lang', '+62(0)487493', '306', 'Mississippi');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (748, 'Prof. Thad VonRueden Sr.', '1-708-006-06', '750', 'Illinois');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (751, 'Heloise Bernhard', '(040)408-515', '666', 'NewHampshire');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (752, 'Mr. Hobart Haag Sr.', '(303)318-259', '793', 'Hawaii');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (760, 'Harold Cronin', '1-927-185-47', '335', 'NewJersey');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (766, 'Addie Mitchell III', '(521)298-955', '970', 'NewYork');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (785, 'Prof. Henderson Leuschke', '608-343-9780', '318', 'Wyoming');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (788, 'Hattie Dicki', '(331)664-570', '109', 'Idaho');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (796, 'Kenyon Stark Jr.', '(237)404-341', '414', 'Minnesota');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (814, 'Laisha Hodkiewicz', '+98(9)839361', '280', 'Hawaii');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (830, 'Erica Konopelski', '279.516.0902', '521', 'Texas');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (831, 'Dr. Gillian Cummings', '(086)801-452', '079', 'Florida');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (838, 'Reva Schiller Sr.', '373-366-0781', '964', 'Idaho');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (842, 'Cathy Lockman', '974-179-9822', '640', 'Oregon');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (844, 'Deondre Kemmer III', '405-775-9795', '107', 'Iowa');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (845, 'Mrs. Rebeka Reichel', '+97(7)379058', '600', 'Oklahoma');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (847, 'Mr. Sammie Harvey', '501.721.9760', '912', 'Arizona');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (855, 'Adelia Ziemann', '03337781112', '358', 'NorthCarolina');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (856, 'Jillian Yundt', '(450)277-855', '340', 'Delaware');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (864, 'Carroll Lindgren PhD', '1-947-799-60', '857', 'NewYork');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (868, 'Arvel Bins', '221-483-2208', '290', 'Florida');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (875, 'Waino Koch', '444-827-1836', '901', 'Oklahoma');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (889, 'Vivien Cummerata II', '603-701-7467', '126', 'Georgia');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (901, 'Liza Franecki', '086-056-7947', '866', 'Connecticut');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (913, 'Mrs. Freida Hermann I', '192.984.2899', '248', 'Colorado');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (947, 'Cory Grimes', '02395547116', '230', 'Maryland');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (957, 'Alvera Swift', '+84(0)698933', '124', 'Delaware');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (958, 'Mrs. Elenor Dare Jr.', '450.457.7845', '487', 'NorthCarolina');
INSERT INTO `VENDOR` (`VENDOR_ID`, `VENDOR_NAME`, `VENDOR_PHONE`, `VENDOR_AREACODE`, `VENDOR_STATE`) VALUES (964, 'Eugenia Pouros', '+98(4)312237', '190', 'Minnesota');


